services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: demodb
    environment:
      MSSQL_SA_PASSWORD: "Password#123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1455:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - trainingnet
  
  webapiapp:
    build:
      context: ../InventoryManagement
      dockerfile: InventoryManagement/Dockerfile
    ports:
      - "8056:8080"
    networks:
      - trainingnet

volumes:
  mssql-data:

networks:
  trainingnet: